name: actions/ci
on: [ push ]
jobs:
  test:
    runs-on: sfdc-hk-ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 1.15.2
    - run: make test
